# See Makefile for the commands that generate Go types from this file.
# This file is referenced by api.yaml.
openapi: 3.0.1
info:
  title: Config types
  version: 1.0.0
  license:
    name: MIT License
    url: https://opensource.org/license/mit
servers: []
paths: {}

components:
  schemas:
    BaseConfigContent:
      type: object
      properties:
        provider:
          description: The SaaS API that we are integrating with.
          example: salesforce
          type: string
        read:
          $ref: '#/components/schemas/BaseReadConfig'
        write:
          $ref: '#/components/schemas/BaseWriteConfig'
        proxy:
          $ref: '#/components/schemas/BaseProxyConfig'

    BaseProxyConfig:
      type: object
      properties:
        enabled:
          type: boolean

    BaseReadConfig:
      type: object
      properties:
        objects:
          type: object
          description: This is a map of object names to their configuration.
          additionalProperties:
            $ref: '#/components/schemas/BaseReadConfigObject'

    BaseReadConfigObject:
      type: object
      properties:
        objectName:
          description: The name of the object to read from.
          example: account
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
        schedule:
          type: string
          description: The schedule for reading the object, in cron syntax.
          example: '*/15 * * * *'
        destination:
          description: The name of the destination that the result should be sent to.
          example: accountWebhook
          type: string
        selectedFields:
          type: object
          description: This is a map of field names to booleans indicating whether they should be read.
          example: '{ phone: true, fax: true }'
          additionalProperties:
            type: boolean
        selectedFieldMappings:
          type: object
          description: This is a map of mapToNames to field names. (A mapTo name is the name the builder wants to map a field to when it lands in their destination.)
          example: '{ phoneNumber: phone, faxNumber: fax }'
          additionalProperties:
            type: string
        history:
          type: string
          description: The history configuration for the object.
          example: '7 days'
    BaseWriteConfig:
      type: object
      properties:
        objects:
          type: object
          description: This is a map of object names to their configuration.
          additionalProperties:
            $ref: '#/components/schemas/BaseWriteConfigObject'

    BaseWriteConfigObject:
      type: object
      properties:
        objectName:
          description: The name of the object to write to.
          example: account
          type: string
          x-oapi-codegen-extra-tags:
            validate: required

    ConfigContent:
      allOf:
        - $ref: '#/components/schemas/BaseConfigContent'
        - type: object
          required:
            - provider
          properties:
            read:
              x-go-type: ReadConfig
            write:
              x-go-type: WriteConfig

    ReadConfig:
      allOf:
        - $ref: '#/components/schemas/BaseReadConfig'
        - type: object
          required:
            - objects
          properties:
            objects:
              additionalProperties:
                x-go-type: ReadConfigObject

    ReadConfigObject:
      allOf:
        - $ref: '#/components/schemas/BaseReadConfigObject'
        - type: object
          required:
            - objectName
            - schedule
            - destination
            - selectedFields
            - selectedFieldMappings

    WriteConfig:
      allOf:
        - $ref: '#/components/schemas/BaseWriteConfig'
        - type: object
          properties:
            objects:
              additionalProperties:
                x-go-type: WriteConfigObject

    WriteConfigObject:
      allOf:
        - $ref: '#/components/schemas/BaseWriteConfigObject'
        - type: object
          required:
            - objectName

    UpdateInstallationConfigContent:
      allOf:
        - $ref: '#/components/schemas/BaseConfigContent'

    UpdateInstallationReadConfig:
      allOf:
        - $ref: '#/components/schemas/BaseReadConfig'

    UpdateInstallationReadConfigObject:
      allOf:
        - $ref: '#/components/schemas/BaseReadConfigObject'
