openapi: 3.0.1
info:
  title: Ampersand public search API
  version: 1.0.0
servers:
  - url: https://search.withampersand.com/v1
paths:
  /projects/{projectIdOrName}/integrations/{integrationId}:
    post:
      summary: Search records
      description: Search records in a SaaS instance.
      operationId: searchRecords
      tags: ["Search"]
      parameters:
        - name: projectIdOrName
          in: path
          required: true
        - name: integrationId
          in: path
          required: true
        - name: groupRef
          in: query
          required: true
          description: The groupRef for the connection.
          example: group-123
          schema:
            type: string
      requestBody:
        description: Search request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        200:
          description: The search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
        400:
          description: The failure response for bad request.
          content:
            application/json:
              schema:
                $ref: "../problem/problem.yaml#/components/schemas/ApiProblem"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "../problem/problem.yaml#/components/schemas/ApiProblem"
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: "../problem/problem.yaml#/components/schemas/ApiProblem"
components:
  schemas:
    SearchRequest:
      title: Search Request
      required:
        - objectName
        - filter
      type: object
      properties:
        objectName:
          type: string
          description: The name of the object to search.
          example: contacts
          schema:
            type: string
        filter:
          type: array
          items:
            $ref: "#/components/schemas/Filter"
          description: The filter to apply to the search.
          example: [{"fieldName": "name", "operator": "equals", "value": "John Doe"}]
          schema:
            type: array
    Filter: 
      title: Filter
      type: object
      required:
        - fieldName
        - operator
        - value
      properties:
        fieldName:
          type: string
          description: The name of the field to filter on.
          example: name
        operator:
          type: string
          description: The operator to use for the filter. Valid operators are: equals, notEquals, contains, notContains, startsWith, endsWith, isNull, isNotNull, isEmpty, isNotEmpty.
          example: equals
        value:
          type: any
          description: The value to filter on. The type of the value is dependent on the field type.
          example: "John Doe"
    SearchResponse:
      title: Search Response
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '../webhook/webhook.yaml#/components/schemas/ResultEntry'