name: Update types in the connectors repo

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  dispatch:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          repository: amp-labs/connectors 
          event-type: run-gen-catalog 
