name: trigger auto-generation of documentation when the openapi spec changes

on:
  push:
    branches:
      # This workflow will run every time you push code to the following branch: `main`
      # Check out GitHub's docs for more info on configuring this:
      # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: trigger generation of api reference pages in docs repo
        run: |
          # Set the required variables
          repo_owner="amp-labs" 
          repo_name="docs"  
          event_type="update-docs-trigger" 

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.AMPERSAND_OPS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}}"
