name: Trigger VS Code Schema Update

on:
  push:
    branches:
      - main
    paths:
      - "manifest/generated/manifest.json"
  workflow_dispatch:

jobs:
  trigger-schema-update:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger schema update in VS Code extension repo
        run: |
          # Set the required variables
          repo_owner="amp-labs" 
          repo_name="vs-code-extension"  
          event_type="update-json-schema" 

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.AMPERSAND_OPS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"
